version: "3.9"

services:
    db:
        container_name: arrebol-db
        image: postgres
        environment:
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"

    php-fpm:
        container_name: arrebol-php-fpm
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: arrebol-nginx
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        links:
            - php-fpm
