version: "3.9"

services:
    ngix:
        image: nginx:latest
        container_name: arrebol-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        container_name: arrebol-php-fpm
        image: php:8-fpm
        volumes:
            - .:/var/www/html
