version: "3.9"

services:
    db:
        container_name: arrebol-db
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"

    php-fpm:
        container_name: arrebol-php-fpm
        image: php:8-fpm
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: arrebol-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        links:
            - php-fpm
